Bumb @status-im/(components|colors|icons) to latest versions
nimbus-gui/nimbus-gui pull request #48
Opened 2024-02-07 18:03 UTC by EmilIvanichkovv

2024-02-07 18:12 UTC, EmilIvanichkovv commented
Goals of this PR:
- [ ] Fixed build
- [ ] UI with the same state as before (but with the latest version of the `status-im/status-web` deps

The package updates resulted in a build failure and issues within the UI. Many of these issues stem from the outdated version of `tamagui` that we've been using. Please make a thorough review of the latest commit, as most of the changes I've made were based on intuition. @HristoNedelkov can you take over from here, please?

2024-02-12 18:53 UTC, RadoslavDimchev requested changes
I found that we can you onPress for tamagui stacks, instead of using div wrapper with onClick.

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/pages/ValidatorOnboarding/ClientSetup/WithdrawalAddress.tsx
This "colorsTyped['red']" is undefined. Nice for adding type instead of leaving any, but is this ok to have imports from react native?

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/components/General/LinkWithArrow.tsx
You can return this navigate handler on the XStack, because we want after click on the arrow also to can link and instead of using onClick, you can use onPress, it is same here.

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/components/General/RightSideBar/ValidatorsTabs/ValidatorListItem.tsx
Same here, you can use onPress and remove div, it is same as onClick event, but it is a tamagui variant.

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/pages/Dashboard/BalanceChartCard/BalanceChartCard.tsx
Use onPress and remove this wrapping div

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/pages/Dashboard/DeviceUptime/DeviceUptime.tsx
onPress and remove div

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/pages/ValidatorOnboarding/KeyGeneration/KeystoreFiles/KeystoreBackupsCard.tsx
Same as above

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/pages/ValidatorOnboarding/KeyGeneration/RecoveryPhrase.tsx
onPress again and remove div

2024-02-12 18:53 UTC, RadoslavDimchev commented on src/pages/ValidatorOnboarding/ValidatorSetup/ValidatorSetup/ExecClientCard.tsx
Here also remove div and use onPress

2024-02-12 19:05 UTC, EmilIvanichkovv commented on src/pages/ValidatorOnboarding/ClientSetup/WithdrawalAddress.tsx
Do not understand what you mean it is undefined?

> is this ok to have imports from react native?

I do not find reason not to

2024-02-12 19:05 UTC, EmilIvanichkovv commented on src/pages/Dashboard/BalanceChartCard/BalanceChartCard.tsx
Good catch

2024-02-12 19:17 UTC, RadoslavDimchev commented on src/pages/ValidatorOnboarding/ClientSetup/WithdrawalAddress.tsx
> Do not understand what you mean it is undefined?
> 
> > is this ok to have imports from react native?
> 
> I do not find reason not to

There is no key "red" in this object

2024-02-12 21:27 UTC, RadoslavDimchev approved these changes
👍

2024-02-13 14:58 UTC, merged