Validator manegement stories and spacing fixes
nimbus-gui/nimbus-gui pull request #84
Opened 2024-03-27 06:13 UTC by HristoNedelkov

2024-03-27 06:45 UTC, RadoslavDimchev requested changes
Why are you imported old things for manage validator?

2024-03-29 08:08 UTC, EmilIvanichkovv requested changes
There seem to have a lot of reverts of @RadoslavDimchev work from the last days. Please sync with him to clear what out

2024-03-29 08:08 UTC, EmilIvanichkovv commented on src/pages/ManageValidator/LeftManage/ValidatorBlueSection/ValidatorBalance.tsx
> +        <Icon src="/icons/suit-guy.png" width={200} height={70}></Icon>
Ditto. This was changed [here](https://github.com/nimbus-gui/nimbus-gui/commit/6a92e4e0b6709162d05969d85faaefad7a293af1#diff-31ee1c410505317957ce3bb2ecd8716bf266b54b65a4149f33f32779a6fe7c0e)

2024-03-29 08:08 UTC, EmilIvanichkovv commented on src/pages/ManageValidator/LeftManage/ValidatorBlueSection/ValidatorBlueSection.tsx
> +    <YStack backgroundColor="#F4F6FE" space={'$2'}>
This is a change introduced by @RadoslavDimchev [here](https://github.com/nimbus-gui/nimbus-gui/commit/e76b4f00a2050b30c728bc8878207adc1af86819) why do you revert it?

2024-04-02 08:47 UTC, closed without merging